### ISSUE TITLE
Not working Covers anymore 

### ISSUE THREAD

**Issue by Julger92** [Kannix2005/homeassistant-selve#23]
**Describe the bug**
See attachement. No of my Covers works anymore. What could be the reason?

![IMG_7025](https://github.com/Kannix2005/homeassistant-selve/assets/112346680/17569742-6546-4eb9-b3fe-a6386d2a7bc8)
![IMG_7027](https://github.com/Kannix2005/homeassistant-selve/assets/112346680/a3319edb-bbc3-4453-aaec-e0cb60443979)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - HomeAssistant Version: [e.g. 1.0.0]
 - OS [e.g. Ubuntu, Hassio, Docker]
 - Used shutters (iveo/commeo) [e.g. 2 x iveo]

**Additional context**

Logger: homeassistant.config_entries
Source: config_entries.py:402 
First occurred: 10:25:21 (2 occurrences) 
Last logged: 10:38:16

Error setting up entry selve for selve
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/selve/__init__.py", line 63, in async_setup_entry
    return await selvegat.async_setup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/selve/__init__.py", line 127, in async_setup
    await self.controller.setup(discover=True)
  File "/usr/local/lib/python3.11/site-packages/selve/__init__.py", line 148, in setup
    await self.discover()
  File "/usr/local/lib/python3.11/site-packages/selve/__init__.py", line 614, in discover
    config: IveoGetConfigResponse = await self.executeCommandSyncWithResponse(IveoGetConfig(i))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selve/__init__.py", line 551, in executeCommandSyncWithResponse
    resp = await self._executeCommandSyncWithResponse(command)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selve/__init__.py", line 570, in _executeCommandSyncWithResponse
    await self._sendCommandToGateway(command)
  File "/usr/local/lib/python3.11/site-packages/selve/__init__.py", line 258, in _sendCommandToGateway
    await asyncio.sleep(0.5)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 649, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

**Comment by frankfrommelt** [comment]
Well, I am using the same versions of the ha components as you. Just updated to core 12.1 yesterday.

For me it is working.
What version of the Selve integration are you using?
When you look at the Selve integration, do you see any blinds?
Maybe during an update there have been new instances created.
What is in the core log, I guess there should be error messages.
   Frank

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
From: Julger92 ***@***.***>
Sent: Sunday, December 10, 2023 9:53:41 AM
To: Kannix2005/homeassistant-selve ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Kannix2005/homeassistant-selve] Not working Covers anymore (Issue #23)


Describe the bug
See attachement. No of my Covers works anymore. What could be the reason?

IMG_7025.png (view on web)<https://github.com/Kannix2005/homeassistant-selve/assets/112346680/17569742-6546-4eb9-b3fe-a6386d2a7bc8>
IMG_7027.jpeg (view on web)<https://github.com/Kannix2005/homeassistant-selve/assets/112346680/a3319edb-bbc3-4453-aaec-e0cb60443979>

To Reproduce
Steps to reproduce the behavior:

  1.  Go to '...'
  2.  Click on '....'
  3.  Scroll down to '....'
  4.  See error

Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

  *   HomeAssistant Version: [e.g. 1.0.0]
  *   OS [e.g. Ubuntu, Hassio, Docker]
  *   Used shutters (iveo/commeo) [e.g. 2 x iveo]

Additional context
Add any other context about the problem here.
